name: Continuous Integration (CI)

on:
  push:
    branches: [ "main" ]

jobs:
  training_job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install MLflow & Dependencies
      run: |
        pip install mlflow dagshub pandas scikit-learn xgboost

    - name: Jalankan MLflow Project
      env:
        # Kita ambil password dari Secret GitHub (Biar aman)
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      run: |
        # Perintah ini akan menjalankan file MLProject yang ada di folder 'MLProject'
        mlflow run MLProject --no-conda --experiment-name "CI_Github_Action"
