name: Continuous Integration (CI)

on:
  push:
    branches: [ "main" ]

jobs:
  training_job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies Lengkap
      run: |
        python -m pip install --upgrade pip
        # Kita install SEMUA library yang mungkin dipakai biar aman
        pip install mlflow dagshub pandas scikit-learn xgboost joblib matplotlib seaborn

    - name: Cek Struktur Folder (Debug)
      run: |
        echo "Isi folder saat ini:"
        ls -R

    - name: Jalankan MLflow Project
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      run: |
        # Perintah ini akan mencari folder 'MLProject' dan menjalankan file di dalamnya
        mlflow run MLProject --env-manager=local --experiment-name "Eksperimen_Skilled_Telco"
