name: CI Pipeline & Docker Build (Advance)

on:
  push:
    branches: [ "main" ]

jobs:
  training_job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow dagshub pandas scikit-learn xgboost joblib matplotlib seaborn

    - name: Login ke Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Jalankan MLflow Project & Build Docker
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      run: |
        # 1. Jalankan Training
        mlflow run MLProject --env-manager=local --experiment-name "Eksperimen_Skilled_Telco"
        
        # 2. Ambil Run ID Terakhir
        LAST_RUN_ID=$(python -c "import mlflow; mlflow.set_tracking_uri('${MLFLOW_TRACKING_URI}'); print(mlflow.search_runs(experiment_names=['Eksperimen_Skilled_Telco'], max_results=1).iloc[0].run_id)")
        
        echo "Run ID ditemukan: $LAST_RUN_ID"
        
        # --- JEDA & CEK ---
        echo "Menunggu DagsHub (60 detik)..."
        sleep 60  # Kita tambah jadi 1 menit biar aman
        
        # 3. DOWNLOAD MANUAL (Jurus Anti-Gagal)
        # Kita paksa download artifact 'model' ke folder lokal bernama 'model_download'
        echo "Mencoba download model ke lokal..."
        mlflow artifacts download --run-id $LAST_RUN_ID --artifact-path model --dst-path ./model_download
        
        # Cek apakah folder berhasil didownload
        ls -R model_download
        
        # 4. Build Docker Image dari Folder LOKAL
        IMAGE_NAME="${DOCKER_USER}/telco-churn-model:v1"
        
        echo "Sedang membuild Docker Image: $IMAGE_NAME ..."
        
        # Perhatikan: --model-uri mengarah ke folder lokal hasil download tadi
        mlflow models build-docker --model-uri "./model_download/model" --name "$IMAGE_NAME"
        
        # 5. Upload ke Docker Hub
        echo "Mengupload ke Docker Hub..."
        docker push "$IMAGE_NAME"
