name: CI Pipeline & Docker Build (Advance)

on:
  push:
    branches: [ "main" ]

jobs:
  training_job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow dagshub pandas scikit-learn xgboost joblib matplotlib seaborn

    - name: Login ke Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Jalankan MLflow Project & Build Docker
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      run: |
        # 1. Jalankan Training
        mlflow run MLProject --env-manager=local --experiment-name "Eksperimen_Skilled_Telco"
        
        # 2. Ambil Run ID Terakhir
        LAST_RUN_ID=$(python -c "import mlflow; mlflow.set_tracking_uri('${MLFLOW_TRACKING_URI}'); print(mlflow.search_runs(experiment_names=['Eksperimen_Skilled_Telco'], max_results=1).iloc[0].run_id)")
        
        echo "Run ID ditemukan: $LAST_RUN_ID"
        
        # --- PERBAIKAN DI SINI: KITA KASIH JEDA 30 DETIK ---
        echo "Menunggu DagsHub memproses artifact..."
        sleep 30
        # ---------------------------------------------------

        # 3. Build Docker Image
        IMAGE_NAME="${DOCKER_USER}/telco-churn-model:v1"
        
        echo "Sedang membuild Docker Image: $IMAGE_NAME ..."
        # Pastikan tetap pakai /model karena di python kamu save ke folder "model"
        mlflow models build-docker --model-uri "runs:/$LAST_RUN_ID/model" --name "$IMAGE_NAME"
        
        # 4. Upload ke Docker Hub
        echo "Mengupload ke Docker Hub..."
        docker push "$IMAGE_NAME"
