name: CI Pipeline & Docker Build (Fix Folder MLProject)

on:
  push:
    branches: [ "main" ]

jobs:
  training_job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow dagshub pandas scikit-learn xgboost joblib matplotlib seaborn

    - name: Login ke Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Jalankan MLflow Project (mlflow run)
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      run: |
        echo "Masuk ke folder project..."
        cd MLProject
        
        echo "Memperbaiki nama file (MLProject -> MLproject)..."
        # Ini trik supaya robot Linux bisa baca file kamu (Case Sensitive)
        if [ -f MLProject ]; then
          mv MLProject MLproject
        fi

        echo "Menjalankan training via MLflow Run..."
        mlflow run . --env-manager=local --entry-point main -P n_estimators=100 -P learning_rate=0.1

    - name: Upload Model Artifact to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: model-hasil-training
        # Path harus ditambah 'MLProject/' karena model tersimpan di dalam folder itu
        path: MLProject/model_docker_local 

    - name: Build & Push Docker Image
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      run: |
        IMAGE_NAME="${DOCKER_USER}/telco-churn-model:v1"
        
        echo "Build Docker Image..."
        # Path model juga harus disesuaikan ke dalam folder MLProject
        mlflow models build-docker --model-uri "./MLProject/model_docker_local" --name "$IMAGE_NAME"
        
        echo "Push ke Docker Hub..."
        docker push "$IMAGE_NAME"
